language: node_js
node_js:
  - "stable"
before_script:
  - cd server
  - npm install
  - npm install express --save
  - npm install --save-dev jest
script:
  - npm test
services:
  - redis-server
  - mongodb